### PR TITLE
Summary functions

### PR DESCRIPTION
**Pull request by bleearmstrong**
This PR adds most of the summary functions from [data wrangling cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf). They work with summarize and mutate. Since it's more or less copying the `dplyr` syntax, it uses R's more functional style as opposed to python's method style (e.g. `mean(X.x)` instead of `X.x.mean()`).

Two big notes: 
1: You may want to cherrypick this PR, since it overrides `min` and `max`. Should they be renamed to something `dfply` specific?

2: I haven't quite figured out `nth`. It's easy enough if there is an nth element, but if there's not an nth element, it should return NA. However, `dfply` doesn't want to play well with try/except, so accessing a non-existent element raises an `IndexError`. Not sure how to get around this until I dive a little more deeply into the delayed evaluation aspect.

Hopefully I got the includes right this time.

### CODE REVIEW

**Comment by bleearmstrong** [comment]
Looks like I'm still unsure as to how to include the summary_functions.py file.

**Comment by kieferk** [comment]
Thanks, they look good. I will figure out the summary_functions.py file (i'll probably just combine it into the summarize.py file). 

I don't think that overriding the built in min(), max(), etc. functions is worth keeping the dplyr syntax the same. My intention wasn't to mimic the syntax exactly, but rather mimic the ease and functionality of the package. I will think of a name for them, or even just leave them out since the built-in Series functions are straightforward.

It would be nice to use try/except logic, but hard for me to say what the problem is (whether it is code I wrote or code in the pandas-ply symbolic module) without seeing the nth function you were having trouble with. If you paste the function here I can try it out.

I'll merge this into develop now since it doesn't conflict with the branch, but probably won't get around to modifying and merging it into master until probably tomorrow morning.

**Comment by kieferk** [comment]
OK so I spent a bunch of time investigating this; the pandas-ply symbolic code is pretty tricky to wrap my head around. I did, however, find a solution to this.

On the develop branch you can see in the most recent few commits some changes to the code. The nth function is in there, and uses a try/except block. I haven't seen your nth function code, but I think that the problem that was probably happening to you as well had something to do with the order of evaluation happening with the symbols. 

I've added a new decorator called `make_symbolic` (may rename it later, not sure if I like that name) which is designed to wrap a function and any symbolic arguments it has in a `symbolic.sym_call` function call. This appears to make sure that the function is chained together correctly with the other operations.  

I took a long look at the pandas-ply code, particularly the `sym_call` function, and figured out that functions taking symbols as arguments sometimes, but not always evaluate correctly. Wrapping the function with `sym_call` explicitly turns the function into a chainable `pandas_ply.symbolic.Call` object.

The nth code now is:
```python
@make_symbolic
def nth(series, n, order_by=None):
    if order_by is not None:
        series = order_series_by(series, order_by)
    try:
        return series.iloc[n]
    except:
        return np.nan
```

And does not cause an indexing error.

I'm definitely keeping this in development for now, since I'm still somewhat uncertain of the structure of the decorator and how symbolics are getting evaluated (despite the tests all passing).

Cheers,
Kiefer

**Comment by bleearmstrong** [comment]
Awesome. My code was essentially the same. Thanks for figuring that out.

**Pull request merged**
